### ISSUE TITLE
HLS stream has great delay

### ISSUE THREAD

**Issue by ReInventTheWheel** [JasonRivers/Docker-nginx-rtmp#16]

**Comment by JasonRivers** [comment]
HLS is delayed because of the way it works, HLS will take the RTMP feed and drop small chunks to disk, and then it creates a playlist of those chunks which it will keep updating as new chunks are created. We have played a little with the settings for this to reduce some latency, but if we go too far then clients buffer all the time due to small video chunks. I will see if there's anything I can do to reduce the latency further than we currently have.

**Comment by ReInventTheWheel** [comment]
Thanks for the reply.
