### ISSUE TITLE
Config rewrite on restart

### ISSUE THREAD

**Issue by Telain** [JasonRivers/Docker-nginx-rtmp#7]
Everytime I restart the docker, nginx.conf is replaced. Can this be altered to not do that?

**Comment by Telain** [comment]
I worked around this for now by defining a run.sh of my own in the docker config.

**Comment by JasonRivers** [comment]
Hi @Telain What configuration is it you need that isn't there? The idea of writing the config at startup is to add in anything the user has put into the environment. I'll look at changing it so that it only does this if the file doesn't exist, this way you can mount with a configuration file and all should work.

**Comment by JasonRivers** [comment]
From 8ae8cf3 you should be able to mount your own config using:
-v /path/to/nginx.conf:/opt/nginx/conf/nginx.conf
the container will now only create this file at startup if the file does not exist.
